volumes:
  db-data:

networks:
  backend:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  # api:
  #   image: danielsantos8/ecommerce-api:1.0.0
  #   build:
  #     context: ./api-js
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - ./api-js/.env
  #   depends_on:
  #     - db
  #   command: sh -c "./wait-for-db.sh"
  #   networks:
  #     - backend

  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   depends_on:
  #     - api
  #   networks:
  #     - backend

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   entrypoint: >
  #     sh -c "sleep 10 &&
  #     certbot certonly --webroot --webroot-path=/var/www/certbot
  #     --email asdanielsantos@gmail.com --agree-tos --no-eff-email
  #     -d fireforgelabs.shop"
  #   networks:
  #     - backend
