services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: ./api-js
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./api-js/.env
    depends_on:
      - db
    command: sh -c "./wait-for-db.sh"
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge
