import type { Metadata } from "next";
import Navbar from "@/components/headers/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
    title: "E-commerce",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <>
            <Navbar />
            <main className="pt-18">{children}</main>
            <Footer />
        </>
    );
}
